### ISSUE TITLE
cargo test --all --all-targets --no-default-features --features serde fails since commit 94ca198b83f036e34650ff82f13b296c7969b9ba

### ISSUE THREAD

**Issue by plugwash** [servo/unicode-bidi#83]
After updating unicode-bidi in Debian to version 0.3.8 we noticed that "cargo test --all --all-targets --no-default-features --features serde" now fails with cargo test --all --all-targets --no-default-features --features serde

    error[E0599]: no function or associated item named `new` found for struct `BidiInfo` in the current scope 
     --> src/lib.rs:912:35
       |
    263 | pub struct BidiInfo<'text> {
          | -------------------------- function or associated item `new` not found for this
        ...
    912 |         let bidi_info = BidiInfo::new(text, None);
        |                                   ^^^ function or associated item not found in `BidiInfo<'_>`

I bisected the regression and found it comes from 94ca198b83f036e34650ff82f13b296c7969b9ba, this seems to be an actual regression, not merely a newly added test.

**Comment by mbrubeck** [comment]
Thanks for the report.  Submitted #84 to fix the test build.

The underlying regression of `--no-default-features` builds was discussed in #78.
